# Site settings
title: Blog do Pedro
description: "Um Blog sem tema unificador"
url: "http://www.pedroh.com.br"
author:
  name: "Pedro Ferreira"
  email: "pedroferreira@ieee.org"
  url: "http://www.pedroh.com.br"

# Build settings
baseurl: "/"  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
